export const RULES_REQUEST = 'RULES_REQUEST'
export const RULES_SUCCESS = 'RULES_SUCCESS'
export const RULES_FAILURE = 'RULES_FAILURE'

export const RULE_REQUEST = 'RULE_REQUEST'
export const RULE_SUCCESS = 'RULE_SUCCESS'
export const RULE_FAILURE = 'RULE_FAILURE'

export const CREATE_RULE_REQUEST = 'CREATE_RULE_REQUEST'
export const CREATE_RULE_SUCCESS = 'CREATE_RULE_SUCCESS'
export const CREATE_RULE_FAILURE = 'CREATE_RULE_FAILURE'

export const UPDATE_RULE_REQUEST = 'UPDATE_RULE_REQUEST'
export const UPDATE_RULE_SUCCESS = 'UPDATE_RULE_SUCCESS'
export const UPDATE_RULE_FAILURE = 'UPDATE_RULE_FAILURE'

export const DELETE_RULE_REQUEST = 'DELETE_RULE_REQUEST'
export const DELETE_RULE_SUCCESS = 'DELETE_RULE_SUCCESS'
export const DELETE_RULE_FAILURE = 'DELETE_RULE_FAILURE'
